### ISSUE TITLE
The parameter 'reports_count' is declared more than once in the parameter list

### ISSUE THREAD

**Issue by clintonm9** [voxpupuli/puppet-module-puppetboard#114] opened 2016-04-15 18:54 UTC
On a fresh install of this package I get this error when declaring? Is this a bug?

**Comment by jyaworski** [comment] 2016-04-15 20:05
Are you using the forge version, or the git version?

**Comment by clintonm9** [comment] 2016-04-15 20:07
I ran "puppet module install puppet-puppetboard" so I am guessing that is forge.

**Comment by jyaworski** [comment] 2016-04-15 20:08
This is a duplicate of #103 then. Closing. For now, use the git version until we get a forge release out with the fix.

**Closed by jyaworski** 2016-04-15 20:08 UTC
